# Generated by Django 5.2.7 on 2025-10-04 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0003_remove_company_manager_remove_company_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='notification_sent',
            field=models.BooleanField(default=False),
        ),
    ]
