# Generated by Django 5.2.7 on 2025-10-04 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0004_booking_notification_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='flight_class',
            field=models.CharField(choices=[('economy', 'Economy'), ('comfort', 'Comfort'), ('business', 'Business')], default='economy', max_length=10),
        ),
    ]
