# Generated by Django 5.2.7 on 2025-10-04 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0005_flight_flight_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='return_flight',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_of', to='flights.flight'),
        ),
    ]
